mirage/mirage-crypto

- mirage-crypto.opam
also mirage-xen-posix and ocaml-freestanding are depopts (and mirage-xen/mirage-solo5 are not needed at all anymore)
> depend on conf-pkg-config, which is executed by the cross-compilation runes

- mirage-crypto.opam
- rng/unix/mirage_crypto_rng_unix.ml
- src/dune
- src/hash.ml
- src/mirage_crypto.mli
- src/native.ml
only `Hash.hash` used sexplib (used by tls), we can just move the code to tls instead and get a sexplib-free mirage-crypto.
> no sexplib in main mirage-crypto anymore

- .travis.yml
so we actually test that (please note that the cirrus runners install zarith-freestanding (and thus ocaml-freestanding) as optional dependencies --> the freestanding sublibraries are already under CI :)
> travis: on ubuntu use mirage-xen-posix and zarith-xen as depopts

- src/ccm.ml
- src/cipher_block.ml
- src/mirage_crypto.mli
- tests/test_cipher.ml
see individual commit messages for more details
> ccm gcm adjustments

- entropy/mirage_crypto_entropy.ml
- src/native/entropy_cpu_stubs.c
check rdrand and rdseed return values (CR=1), as recommended by Intel (https://software.intel.com/en-us/articles/intel-digital-random-number-generator-drng-software-implementation-guide)
detect bad rdrand on ryzen 3000 (which returns all-ones) and disable there
> entropy adjustments: check return value of rdrand/rdseed (and retry up to 10 times), cope with AMD ryzen 3000 bug

- mirage-crypto-pk.opam
- pk/common.ml
- pk/dh.ml
- pk/dsa.ml
- pk/dune
- pk/mirage_crypto_pk.mli
- pk/rsa.ml
- pk/z_extra.ml
- tests/test_dh.ml
- tests/test_dsa.ml
- tests/test_rsa.ml
validate before constructing public and private keys. use result instead of exceptions in of_exp, of_prime
remove well_formed, which is now implicit.
> pk: make private and public key private structures

- .github/workflows/test.yml
- CHANGES.md
- mirage-crypto-rng.opam
- rng/unix/discover.ml
- rng/unix/dune
- rng/unix/mc_getrandom_stubs.c
- rng/unix/mirage_crypto_rng_unix.ml
- rng/unix/mirage_crypto_rng_unix.mli
Need this to release conduit (which needs Windows support as well).  It also fixes a bug in the C stubs, and adds GH Actions CI so that we can test Windows in CI as well.
> Add Windows support

- mirage-crypto-pk.opam
- pk/rsa.ml
- src/mirage_crypto.mli
- src/uncommon.ml
> Replace ct_find_uint8 by Eqaf_cstruct.find_uint8

- mirage-crypto-entropy.opam
- mirage-crypto-pk.opam
- mirage-crypto-rng.opam
- mirage-crypto.opam
- pk/dh.ml
- pk/rsa.ml
- rng/mirage_crypto_rng.ml
- src/cipher_block.ml
- src/dune
- src/mirage_crypto.mli
- src/uncommon.ml
> mirage-crypto: remove ocplib-endian dependency, use Bytes.set_int64 in Counters (also remove Uncommon.Option in favour of stdlib)

- README.md
- config/cfg.ml
- config/dune
- entropy/mirage_crypto_entropy.ml
- mirage-crypto.opam
- src/cipher_block.ml
- src/dune
- src/native.ml
- src/native/aes_aesni.c
- src/native/aes_generic.c
- src/native/detect_cpu_features.c
- src/native/entropy_cpu_stubs.c
- src/native/ghash_generic.c
- src/native/ghash_pclmul.c
- src/native/mirage_crypto.h
- src/native/misc.c
- src/native/misc_sse.c
Hi !
This PR adds runtime detection of CPU features.
Both accelerated and generic functions are built and linked. This is implemented with a global variable checked on every call.
The detection is done at initialization time using the library `cpuid`.
Running the all the benchmarks in `bench/` either shows no difference or a slight decrease in performances (consistent 1% on sha1, too much noise on others).
I first tried using modules ([on this branch](https://github.com/mirage/mirage-crypto/compare/master...Julow:runtime-cpuid)) and selecting the right function at the beginning.
This was slower because calls to external functions were no longer inlined (a closure and `caml_apply` indirections)
The cpuid library allocates (around 3Kb) data structures that are only needed once but not …
> Runtime detection of CPU features

- .travis.yml
the macos runner has been removed since GitHub actions are executed on that platform
> travis: test on xenial and bionic, test on arm64

- src/native/bitfn.h
/cc @avsm IMHO better to remove the code for now, and once we have CI and the need for a native windows port, we can work on that.
> bitfn: remove MSC support (untested, likely incomplete, not in CI)

- rng/unix/dune
- src/dune
thanks to @samoht for the hint (I tested this locally, and a `dune build --verbose` showed me `-Werror`, a `dune build --profile=release --verbose` not -- I'm not sure whether it is correct, though)
> in development mode, add -Werror to CFLAGS

- freestanding/dune
- src/dune
- src/native/aes_aesni.c
- src/native/ghash_ctmul.c
- src/native/ghash_generic.c
- xen/dune
this should fix #60 //cc @TImada -- the ghash implementation is taken from BearSSL and permissively licensed
the tests are passing :)
there remaining issue is that we do not have a 32bit CI. I have tested this PR manually on a ocaml-variants.4.09.1+32bit switch on x86.
> fix 32 bit support (ghash_ctmul: a ghash implementation from BearSSL that works on 32 bit LE platforms)

- .github/workflows/test.yml
- .travis.yml
- CHANGES.md
- mirage-crypto-rng-mirage.opam
- rng/entropy.ml
- rng/fortuna.ml
- rng/lwt/mirage_crypto_rng_lwt.ml
- rng/lwt/mirage_crypto_rng_lwt.mli
- rng/mirage/dune
- rng/mirage/mirage_crypto_rng_mirage.ml
- rng/mirage_crypto_rng.mli
- rng/rng.ml
- rng/unix/mirage_crypto_rng_unix.ml
- tests/dune
- tests/test_entropy.ml
- tests/test_rsa.ml
Calling Lwt.async and Lwt_unix.Enter_iter_hooks.add_first does not need to be
inside of the Lwt_main.run. This allows library code to execute
Mirage_crypto_rng_lwt.initialize () at top level.
Initialization is only done once (the `running` (bool ref) is used to figure out
whether initialize was already called before).
> Mirage_crypto_rng_lwt.initialize now returns unit instead of unit Lwt.t

- mirage-crypto-rng-mirage.opam
- mirage-crypto-rng.opam
what happened:
- mirage outputs a dependency (when using the random device) on mirage-crypto-rng ~min:"0.7".
- it uses Mirage_crypto_rng_mirage.initialize () (from the mirage-crypto-rng.mirage sublibrary)
now, that sublibrary is gone in 0.8, and part of the separate mirage-crypto-rng-mirage package. since existing mirage tools do not emit an upper bound for the dependency, we need to ensure that no 3.7 unikernel will use mirage-crypto-rng.0.8 (otherwise a link failure will occur that mirage-crypto-rng.mirage does not exist).
> mirage-crypto-rng-mirage: require mirage-runtime 3.8.0 to avoid broken installations, mirage-crypto-rng: conflict with mirage-runtime <3.8.0

- CHANGES.md
- src/native/entropy_cpu_stubs.c
- src/native/ghash_generic.c
- src/native/poly1305-donna.c
Implementation of rtdsc based on clang's builtin version and from gperftools at https://chromium.googlesource.com/external/gperftools/+/master/src/base/cycleclock.h
Fixes #75
Just testing this on the ocaml-ci first so that we can have ppc64 CI before undrafting this.
> add ppc64le support

- rng/entropy.ml
- rng/mirage_crypto_rng.mli
- src/native.ml
- src/native/entropy_cpu_stubs.c
- src/native/poly1305-donna-32.h
- src/native/poly1305-donna-64.h
- src/native/poly1305-donna.c
- tests/dune
- tests/test_entropy.ml
- tests/test_entropy_collection.ml
- use `Val_long` in cycle_counter on powerpc64
- mark poly1305 functions static (alternate fix for #77)
> new test_entropy: testing bootstrap function and timer (cycle counter) to not produce the same output on two subsequent calls

- src/chacha20.ml
this avoid accessing memory which is not necessarily ours. without this fix, segmentation faults may be triggered.
the issue if the encrypted data is not of block size (=64 byte), processing the last buffer will access up to 63 byte of memory which is not properly mapped.
bug is present since introduction of chacha20 in 0.8.1.
> mirage-crypto: chacha20 avoid accessing memory which is not mapped

- .travis.yml
The actual issue is that zarith-freestanding which modifies the META file of zarith are not properly removed (the opam checksum seems to use modification times, and this changes for the reasons above). Thus, the `opam remove zarith` step fails, and the subsequent `opam install zarith` errors with "already installed" (since the META file for zarith is present).
The actual fix would be to get rid of our hacked together zarith "cross-compilation" schemes, which eventually will be a topic once zarith switched to dune as build system and MirageOS 4 is in shape.
> travis: disable testrun on arm64 with depopts

- .github/workflows/esy.yml
- config/cfg.ml
This allows to cross-compile from x86_64 -> ARM64.
> misc: detect CPU architecture from C compiler

- .github/workflows/esy.yml
This should fix the cross compile CI and make it stable, as the `generate` tool actually depends on `mirage-crypto` after the update the old patch broke.
This shouldn't happen anymore as `mirage-crypto` now has no patch, but if it starts to fail most of the time is updating it to the latest commit should be enough
> ci: fix cross compile

- .github/workflows/test.yml
- .github/workflows/windows.yml
- .travis.yml
- mirage-crypto-rng-async.opam
- rng/async/dune
- rng/async/mirage_crypto_rng_async.ml
- rng/async/mirage_crypto_rng_async.mli
- tests/dune
- tests/test_entropy_collection_async.ml
This is an implementation of the async-analogue of `Mirage_crypto_rng_lwt`. It's exposes a single `initialize` function that schedules several periodic jobs to collect entropy from the system and feed it into the `Entropy` module for use by the PRNGs.
I haven't tested this yet, but wanted to throw this up here to gauge whether this would be a welcome contribution. If this looks good, I will follow it up with getting @dinosaure's async ocaml-tls implementation into a state where it can be merged into that project as well.
> mirage-crypto-rng-async

- rng/async/mirage_crypto_rng_async.ml
- rng/entropy.ml
- rng/lwt/mirage_crypto_rng_lwt.ml
- rng/mirage/mirage_crypto_rng_mirage.ml
- rng/mirage_crypto_rng.mli
- tests/dune
- tests/test_entropy_collection.ml
This fixes #94, since register_source is called only once for the rdrand task.
> mirage-crypto-rng: revise Entropy.cpu_rng to delay entropy feeding.

- mirage-crypto-rng-mirage.opam
- rng/async/mirage_crypto_rng_async.ml
- rng/entropy.ml
- rng/lwt/mirage_crypto_rng_lwt.ml
- rng/mirage/mirage_crypto_rng_mirage.ml
- rng/mirage_crypto_rng.mli
- tests/test_entropy.ml
To avoid scheduling timers that do no work, require client code to match on the presence of `cpu_rng` support before attempting to use it.
It appears that `cpu_rng_bootstrap` was kindof already doing this, but with an exception. In this cases, this PR just makes what's going on a little more explicit.
> require client code to match on cpu_rng support

- config/cfg.ml
- freestanding/Makefile
- freestanding/dune
- src/dune
- src/native/bitfn.h
- src/native/chacha_generic.c
(with -O3 -mssse3) to the SSSE3 PSHUFB instruction (at compile time), which is
unavailable on CPUs without SSSE3 (such as AMD Phenom II X4).
Instead, use bswap inline assembly - this is available on CPUs and not optimized
to an SSSE3 insruction. The peformance difference (with bench/speed.exe sha256)
is negligible. This should bring us back to "compile on any CPU, run anywhere"
(optimized code is used if at runtime the respective CPU features (SSSE3,
PCLMULQ, AESNI) are present - the optimized code is always generated (on X86)).
This fixes #93.
> bswap32/64: avoid __builtin_bswap since this is optimized by the C compiler to an SSSE3 instruction

- ec/mirage_crypto_ec.ml
- ec/mirage_crypto_ec.mli
we're using the proven constant-time fiat-crypto primitives, no blinding needed
> mirage-crypto-ec: remove blinding for sign

- .github/workflows/esy.yml
- esy@0.6.8 had a bug caused on invalid symlink, that was rarely triggered outside of cross compilation, with `esy@0.6.10` that was fixed
- because `reason-mobile` itself depends on mirage-crypto this CI should be using resolutions and it was not
- added mirage-crypto-ec on the cross compile list
- added a cross OS case, `macOS -> Android ARM64`
- added `macos.arm64` as a target, this was also checked locally from `Linux -> macOS ARM64` but this cannot be supported on a CI
> fix CI esy cross compile and add macOS ARM64 as target

- ec/mirage_crypto_ec.ml
- tests/test_ec.ml
- tests/test_ec_wycheproof.ml
Their byte length may be shorter than the modulus n. Previously this lead to an
exception. Now r and s are zero-padded (on the left). A regression test
(out of experiments with X.509) is added.
Also, remove size checks from the wycheproof tests (superfluous).
> mirage-crypto-ec: fix regression in Dsa.verify if r or s are short

- ec/mirage_crypto_ec.ml
- ec/native/curve25519_stubs.c
- tests/test_ec.ml
Looks like I'm always making the same mistakes (and should really find (or develop) tooling which is more strict when passing pointers from OCaml to C): when passing a Cstruct.t (well, the underlying buffer), take care to add the "off" to the pointer. I reviewed the Mirage_crypto_ec module (with the assumption that Cstruct.create will always create something with off = 0) and couldn't find more cases where the off needs to be added (the tradeoff is clearly "number of arguments passed from OCaml to C").
Anyways, this PR contains some fixes, and when I reviewed the NIST curves I spotted some easy small pieces where to avoid allocations.
> Fix x25519 and ed25519 if Cstruct with off <> 0 is given as input

- mirage-crypto.opam
- src/native/entropy_cpu_stubs.c
As reported and investigated by @adams-1979 in #113, reading the virtual tick
count on arm32 is only accessible in kernel mode.
> mirage-crypto-rng: on arm32, only read the virtual count if we're in kernel mode

- src/native/des_generic.h
> mirage-crypto: compatibility with gcc11 (-Warray-parameters)

- CHANGES.md
- ec/dune
When using `mirage-crypto-ec` with Mirage 4, I've encountered build failures as `mirage_crypto.h` couldn't be found when building `mirage-crypto-ec`'s stubs. Indeed `dune` does not deduce from the `-I../src/native` flag that it has to track `../src/native` as a dependency folder. 
Instead the `include_dirs` option should be used: that's what this PR is about. 
In the opam world this hasn't been a problem because the dune file in `ec-freestanding` correctly specifies the dependency. 
For more information on the dune options for C compilation: https://dune.readthedocs.io/en/stable/concepts.html#foreign-stubs
> Fix C stubs dependency specification in mirage-crypto-ec

- .github/workflows/esy.yml
This should fix the cross-compile CI which was broken because of the bump in OCaml version on reason-mobile to 4.12.
And it also adds android.armv7a as a target on the CI, I'm not sure if mirage-crypto currently supports 32bits but it's a good thing to have a CI to a weird Linux running armv7
> Cross compile to Android ARMv7a

- src/native/entropy_cpu_stubs.c
- src/native/mirage_crypto.h
Tested on Hifive Unmatched, needed to define the preprocess macro that defines this as ARCH_64BIT and implement mc_cycle_counter for RV64. `dune runtest` passes.
This is the bare minimum to get it working, I haven't (yet) implemented any accelerated instructions (there should be at least an AES extension supported by this CPU).
I didn't implement RV32 support: that needs reading both `rdcycle` / `rdcycleh` and dealing with overflow, I do not have any RV32 hardware to test on, and I think that most desktop/server-class CPUs will be 64-bit, 32-bit RISC-V is mostly for MCUs.
Also done some tests in utop to confirm that cycles gives reasonable looking answers:
```
external cycles : unit -> int = "mc_cycle_counter";;
cycles () - cycles ();;
- : int = 255
cycles () - cycles ();;
- : int = 308 …
```
> Initial RISC-V support

- src/native/entropy_cpu_stubs.c
- src/native/mirage_crypto.h
The two commits correct the compile failures of mirage-crypto on the IBMz s390x architecture.
Note that the STCK instruction used in the cycle count implementation guarantees a globally unique result, which is expensive. If that is not needed, STCKF instruction is less expensive.
Also s390x has the PRNO instruction to provide a pseudo-random number, if that would be useful in the other prng functions of the cpu entropy stubs file.
> Add s390x enablement to mirage-crypto

- config/cfg.ml
see https://github.com/ocaml-multicore/ocaml-multicore/issues/574
please confirm that this will be what OCaml-multicore will need and use.
//cc @Engil @kayceesrk @avsm @Sudha247
> multicore requires c11 (using the _Atomic keyword in typedefs)

- mirage-crypto-rng-mirage.opam
- tests/test_entropy_collection.ml
> adapt to mirage-unix 5.0.0

- .github/workflows/test.yml
- .github/workflows/windows.yml
//cc @avsm @smorimoto to me it looks like the github actions do not compile the code and run the tests at the moment!?
> github actions: actually build the code and execute the tests

- rng/async/mirage_crypto_rng_async.ml
- rng/mirage/mirage_crypto_rng_mirage.ml
- rng/mirage_crypto_rng.mli
- rng/rng.ml
Streamline the semantics of the initialize and entropy feeding.
> Rng improvements

- .cirrus.yml
- .test-mirage.sh
- dune-project
- mirage-crypto-ec.opam
- mirage-crypto-pk.opam
- mirage-crypto-rng-async.opam
- mirage-crypto-rng-mirage.opam
- mirage-crypto-rng.opam
- mirage-crypto.opam
//cc @TheLortex applying your suggestion from https://github.com/mirage/mirage/issues/1346 -- but somehow the CI fails since now a `mirage build` attempts to cross-compile everything, and not only the unikernel.
Also, in the generated `Makefile` (at top level) the `build` target omits the `-f mirage/config.ml` -- is this intentional?
> Ci use mirage4

- .cirrus.yml
- .github/workflows/test.yml
- .github/workflows/windows.yml
- mirage-crypto-ec.opam
- mirage-crypto-rng-eio.opam
CI: remove alpha hacks now that ocaml 5 is released
also setup 4.13 and 4.14 runners in github actions
> mirage-crypto-rng-eio: require ocaml 5, and dune 2.7

- rng/lwt/mirage_crypto_rng_lwt.ml
- rng/lwt/mirage_crypto_rng_lwt.mli
- rng/mirage/mirage_crypto_rng_mirage.mli
- rng/unix/mirage_crypto_rng_unix.ml
- rng/unix/mirage_crypto_rng_unix.mli
- tests/test_ec.ml
- tests/test_pk_runner.ml
- tests/test_random_runner.ml
This breaks all clients (API changes). May go smooth with #158 and #138.
> [API change] rng: unify API for initialize, as reported in #160

- bench/speed.ml
- src/aead.ml
- src/ccm.ml
- src/chacha20.ml
- src/cipher_block.ml
- src/mirage_crypto.mli
- tests/test_cipher.ml
this provides CCM only with mac length / tag size of 16 bytes, all other possible mac sizes are not exposed.
first commit is first half of #73
> mirage-crypto: improve AEAD API, provide tag_size and of_secret

- rng/unix/mc_getrandom_stubs.c
- src/native/des_generic.c
- src/native/des_generic.h
- src/native/entropy_cpu_stubs.c
Modern compilers emit warnings when using K&R C function prototypes and functions taking `()` instead of void for no parameters.
> Stricter C function prototypes

- rng/unix/mc_getrandom_stubs.c
I just added support for __DragonFly__ macro meaning the system is DragonFlyBSD, where getrandom() is the same as for OpenBSD
> random support for dflybsd

- CHANGES.md
- mirage-crypto-rng-eio.opam
- rng/eio/dune
- rng/eio/mirage_crypto_rng_eio.ml
- rng/eio/mirage_crypto_rng_eio.mli
This PR improves mirage-crypto-rng-eio's portability by making it not depend on system features. 
Instead of depending on mtime.clock.os, the user should provide a monotonic clock implementation as part of the `env`ironment variable.
> mirage-crypto-rng-eio: use monotonic clock from eio's environment instead of mtime 

- mirage-crypto-rng-eio.opam
- rng/eio/mirage_crypto_rng_eio.ml
- rng/eio/mirage_crypto_rng_eio.mli
Eio 0.12 no longer uses OCaml objects for OS resources. This requires a minor change to mirage-crypto-rng-eio to use the new variant types instead.
(tested using my [Eio 0.12 branch of ocaml-tls](https://github.com/talex5/ocaml-tls/tree/eio))
> Update to Eio 0.12

- config/cfg.ml
- ec/dune
- rng/unix/dune
- src/dune
> avoid stringop-overflow warning on ppc64, s390x

- config/cfg.ml
this is a big hammer which makes the code slower.
but better slow code than not working code. there's hope that apple will eventually fix their llvm.
> on macos (arm64), avoid -O3 due to miscompilations

- rng/unix/mc_getrandom_stubs.c
I currently working on getting Octez (Tezos) to work on NetBSD. Today I successfully built mirage-crypto-rng with this change. I have not been able to do much testing.
> Add NetBSD to the list of BSD OS in define

- rng/fortuna.ml
@palainp observed lots of 2 byte allocations (with malloc, via bigarray). The root cause is the `add` function in our Fortuna module.
This PR uses instead a global pre-allocated buffer. This is likely fine for OCaml 4, but will be troublesome (a data race) when OCaml 5 (see #186) is considered, or any other multi-threading preemption setup.
It is not 100% clear how to move forward. One part is to document "mirage-crypto is not SMP safe", and if someone wants to use it in such a system, they should guard functions with mutexes.
What does the way ahead mean? We have observed that using "cstruct.t" may have been not the wisest choice from early on, and settling on bytes/string would be more wise (in terms of GC friendlyness). We also observe that a "domain-local variable" (i.e. `__thread` in …
> Allocate less in Fortuna

- bench/dune
- bench/speed.ml
- mirage-crypto.opam
this adds sign and verify operations of the nist curves to bench/speed.ml
> add EC to bench/speed

- ec/dune
- ec/mirage_crypto_ec.ml
- ec/mirage_crypto_ec.mli
- ec/native/curve25519_stubs.c
- ec/native/inversion_template.h
- ec/native/np224_stubs.c
- ec/native/np256_stubs.c
- ec/native/np384_stubs.c
- ec/native/np521_stubs.c
- ec/native/p224_stubs.c
- ec/native/p256_stubs.c
- ec/native/p384_stubs.c
- ec/native/p521_stubs.c
- src/native/mirage_crypto.h
This PR wants to delete more and more an usage of `Cstruct.t`. The goal of it is to give an opportunity to use `bytes` instead of `Cstruct.t`. Indeed, in a certain usage, `mirage-crypto-ec` allocates too many `Cstruct.t` which put a huge pressure on the GC. In  some of my stress test, I finally get an `Out_of_memory` exception and an introspection of the memory consumption shows me that `mirage-crypto-ec` allocates 26 % of what I used and most of these objects:
1) are a small bigarray
2) come from this code
This PR is a draft to **internally** uses `bytes` and keep the same interface with a systematic derivation of functions with `bytes`. Then, C calls use only `bytes` instead of `Cstruct.t`.
I will come back with some statistics to see if this PR change something about allocations or …
> Replace the internal usage of Cstruct.t by the bytes type

- ec/mirage_crypto_ec.mli
//cc @edwintorok since you mentioned this in https://discuss.systems/@edwintorok/111925959867297453 - would this warning suite you?
I'm still unsure what advise to give to be honest: on the one side, it looks that these attacks are local -- thus in a multi-tenant setup, just don't do crypto ;) -- on the other side, asking a developer to select a `k` is something they can easily get wrong as well.
So, below the line: should we switch by default to a random `k`? Should we warn about multi-tenant systems explicitly?
The mitigation you mention "validating that the ciphertext (public key) consists of a pair of linearly independent points of the correct order 3e" is obviously something we can implement (enabled by default) -- maybe measure the performance impact?
Also, you mention blinding, and …
> mirage-crypto-ec: warn about power/timing analysis on k in sign

- mirage-crypto-ec.opam
- tests/dune
- tests/test_ec_wycheproof.ml
> mirage-crypto-ec test: avoid gmp dependency

- .github/workflows/dkml.yml
- ci/build-test.sh
> windows/dkml: opam install with deps-only and with-test only packages to test, deps-only for only build

- src/native/entropy_cpu_stubs.c
rdcycle is privileged since kernel 6.6, resulting in SIGILL:
https://buildd.debian.org/status/fetch.php?pkg=ocaml-mirage-crypto&arch=riscv64&ver=0.11.2-1%2Bb3&stamp=1708088363&raw=0
> riscv64: Replace rdcycle64 with rdtime64

- .github/workflows/test.yml
- .github/workflows/windows.yml
- bench/speed.ml
- mirage-crypto.opam
- src/chacha20.ml
- src/mirage_crypto.mli
- src/native.ml
- src/native/bitfn.h
- src/native/chacha.c
- src/native/chacha_generic.c
- src/native/mirage_crypto.h
- src/native/misc.c
- src/native/misc_sse.c
- src/native/poly1305-donna.c
- src/poly1305.ml
- tests/test_cipher.ml
- tests/test_common.ml
Performance improvement around 2.5x
Worth to gather some more statistics hereof, and the question how to move forward - I can see two ways:
- preserve old API, add some functions (adds noise)
- first reimplement stuff without Cstruct, preserve old API, then cut a release where the API doesn't include cstruct
WDYT?
main branch (28f8cde5ff3197e6383a935037725ab34ab32485)
16:  11.686102 MB/s  (2318663 iters in 3.028 s)
64:  44.914143 MB/s  (2248341 iters in 3.055 s)
256:  111.408313 MB/s  (1464243 iters in 3.209 s)
1024:  190.362636 MB/s  (530561 iters in 2.722 s)
8192:  235.326363 MB/s  (81843 iters in 2.717 s)
this PR (with using the ad-hoc API enc_auth_str):
16:  26.288283 MB/s  (5247580 iters in 3.046 s)
64:  99.922308 MB/s  (4995212 iters in 3.051 s)
256:  204.388046 MB/s  (2405283 iters …
> Chacha20-Poly1305: use string instead of cstruct

- ec/mirage_crypto_ec.ml
- pk/dsa.ml
- pk/rsa.ml
- rng/entropy.ml
- rng/fortuna.ml
- rng/hmac_drbg.ml
- rng/mirage_crypto_rng.mli
- rng/rng.ml
- src/ccm.ml
- src/cipher_block.ml
- src/native.ml
- src/native/mirage_crypto.h
- src/native/misc.c
- src/native/misc_sse.c
- tests/test_entropy.ml
this should fix most of #186 -- performance-wise (tested on fortuna), this gives some speedup (but obviously should be tested a bit more)
//cc @reynir @dinosaure
> avoid global buffers

- ec/mirage_crypto_ec.ml
`Cstruct.create` does this. If we don't initialize bytes with '\000', `Field_element.zero` can be something else than '\000'. It's a fix for mirleft/ocaml-x509#167.
> Set a new bytes used for elliptic curves computations to '\000'

- ec/mirage_crypto_ec.ml
- ec/mirage_crypto_ec.mli
- tests/test_ec.ml
Closes #228 
Closes #105 
During K generation, we need to retrieve `l` bits from RNG (where `l` is 256, 384, 521).
Currently, we take `ceil(l / 8)` whole bytes and call it a day. This works fine when `l` is a multiple of 8, but for `l = 521` this generates 7 bits of garbage, which make it very likely the generated vector is over 2^521. When this happens, we loop and retry until we're lucky, which is a lot of busy work for nothing (and makes the time to generate `k` fluctuate wildly, see #228).
This PR truncates the generated vector to keep only the `l` leftmost bits, as per RFC 6979, which:
- makes the generated `k` correct on the first try most of the time, like the other curves
- makes the time of signature fluctuate way less (see #228)
- makes the formerly disabled test vectors for …
> [ec] Handle K_gen correctly for bitlen mod 8 <> 0

- .cirrus.yml
- .test-mirage.sh
- mirage/config.ml
- pk/rsa.ml
- rng/entropy.ml
- src/ccm.ml
- src/mirage_crypto.mli
- src/poly1305.ml
- src/uncommon.ml
> minor updates

- mirage-crypto-ec.opam
- tests/dune
- tests/test_ec_wycheproof.ml
ASN1-combinators no longer depends on zarith & gmp, so we can simply use it and avoid handcrafted ASN1 parsers.
> tests, mirage-crypto-ec: use asn1-combinators again

- .github/workflows/test.yml
- .github/workflows/windows.yml
- ec/mirage_crypto_ec.ml
- mirage-crypto-ec.opam
- mirage-crypto-pk.opam
- mirage-crypto-rng-async.opam
- mirage-crypto-rng-lwt.opam
- mirage-crypto-rng-mirage.opam
- mirage-crypto-rng.opam
- mirage-crypto.opam
- pk/rsa.ml
- pk/z_extra.ml
- src/cipher_block.ml
- src/cipher_stream.ml
- src/uncommon.ml
- tests/test_ec_wycheproof.ml
~~somehow this seems to require on my laptop the `(modes native)` for all the test executables, as proposed in https://github.com/mirage/mirage-crypto/pull/227/commits/764ccde05e8e866d1ab79620b2aa3f3aedd66dad (part of #227)~~
just a dune issue, https://github.com/ocaml/dune/issues/9979 -- let's not bother
> Require OCaml 4.13 and remove local overrides

- bench/speed.ml
- src/aead.ml
- src/ccm.ml
- src/chacha20.ml
- src/cipher_block.ml
- src/cipher_stream.ml
- src/mirage_crypto.mli
- src/native.ml
- src/native/ghash_ctmul.c
- src/native/ghash_generic.c
- src/native/ghash_pclmul.c
- src/native/mirage_crypto.h
- src/native/misc.c
- src/native/misc_sse.c
- src/native/poly1305-donna.c
- src/poly1305.ml
This avoids buffer allocations. There are as well unsafe functions exposed for elevated performance.
Reviews welcome, this is WIP since for now only ECB and ECB modes have this new interface (still missing CTR, GCM, CCM). Will continue work on that. Will superseed #204 (at a future point in time).
> provide ciphers with {de,en}crypt_into functionality

- src/ccm.ml
- tests/test_cipher.ml
The issue were missing offsets, both if multiple blocks were encrypted/decrypted and when unaligned data (i.e. not a multiple of block_size) was encrypted and decrypted.
//cc @reynir @dinosaure
> fix CCM, as discovered when porting TLS to string

- ec/mirage_crypto_ec.ml
- ec/mirage_crypto_ec.mli
> mirage-crypto-ec: provide Dh.secret_to_octets

- rng/unix/mc_getrandom_stubs.c
Since windows filesystem is case insensitive and, AFAIK, `windows.h` is always lowercase in MinGW distributions, using a lowercase include will work on both transparently.
Currently:
```
mc_getrandom_stubs.c:60:10: fatal error: Windows.h: No such file or directory
60 | #include <Windows.h>
|          ^~~~~~~~~~~
```
> Mingw friendly case for includes.

- rng/async/mirage_crypto_rng_async.ml
- rng/dune
- rng/eio/mirage_crypto_rng_eio.ml
- rng/entropy.ml
- rng/lwt/mirage_crypto_rng_lwt.ml
- rng/miou/mirage_crypto_rng_miou_unix.ml
- rng/mirage_crypto_rng.mli
- src/native/entropy_cpu_stubs.c
- Previously, a return value of "0" was treated specially, but rdrand/rdseed may return 0!
- If there's a failure in rdrand/rdseed during cpu_rng_bootstrap, raise an exception
- If there's a failure during the periodic reseeding (timer initiated feeding of all pools), ignore it (for now!?)
//cc @edwintorok addresses #251 -- though I'm not yet happy with the `cpu_rng` failure case // `feed_pools` error case. I'm uncertain what to do:
- do a while true, potentially leading to a busy loop if rdrand/rdseed keeps on giving no data
- raise an exception and exit - which may be inconvenient for the application developer
- call rdseed/rdrand (the other instruction) as an attempt to delay the error condition
> Handle CPU_RNG failures in OCaml:

- CHANGES.md
- rng/unix/mc_getrandom_stubs.c
- src/native/entropy_cpu_stubs.c
Fixes the following:
1. Android 27 and earlier do not have `getrandom` but there is a recommended alternative. https://android.googlesource.com/platform/bionic/+/02ce401d1e2b31586c94c8b6999364bbbce27388/libc/include/sys/random.h
2. MSVC needed a definition for `fill_bytes`.
> Fixes for the less common platforms

- ec/mirage_crypto_ec.ml
- tests/test_ec.ml
The (de-)compression code for ECDSA public keys doesn't use the least significant byte for extracting the parity bit, but the second-least instead, which results in the wrong `0x02`/`0x03` prefix with 50% chance. (Probably the result of some former refactoring.) Because de- and compression code is consistently wrong, the test didn't fail.
This change fixes the compression code, adds an independent prefix check in the compression test and repeat the test 20 times to make sure it hits.
> mirage-crypto-ec: fix ECDSA public key compression
